# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_yinyang_scaled_dataset.ipynb.

# %% auto 0
__all__ = ['reshape_interleave_time', 'reshape_interleave_state', 'reshape_append_time', 'reshape_append_state']

# %% ../nbs/06_yinyang_scaled_dataset.ipynb 4
import torch
import einops

# %% ../nbs/06_yinyang_scaled_dataset.ipynb 30
def reshape_interleave_time(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> s (i t)")

# %% ../nbs/06_yinyang_scaled_dataset.ipynb 31
def reshape_interleave_state(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> (s t) i")

# %% ../nbs/06_yinyang_scaled_dataset.ipynb 32
def reshape_append_time(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> s (t i)")

# %% ../nbs/06_yinyang_scaled_dataset.ipynb 33
def reshape_append_state(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> (t s) i")
