# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_scaled_dataset.ipynb.

# %% auto 0
__all__ = ['reshape_interleave_time', 'reshape_interleave_state', 'reshape_append_time', 'reshape_append_state']

# %% ../nbs/05_scaled_dataset.ipynb 3
import torch
import einops

# %% ../nbs/05_scaled_dataset.ipynb 23
def reshape_interleave_time(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> s (i t)")

# %% ../nbs/05_scaled_dataset.ipynb 24
def reshape_interleave_state(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> (s t) i")

# %% ../nbs/05_scaled_dataset.ipynb 25
def reshape_append_time(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> s (t i)")

# %% ../nbs/05_scaled_dataset.ipynb 26
def reshape_append_state(
    x: torch.Tensor,  # Input tensor
):
    return einops.rearrange(x, "i t s -> (t s) i")
