# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_yinyang_pykoopman.ipynb.

# %% auto 0
__all__ = ['inference_with_koopman']

# %% ../nbs/07_yinyang_pykoopman.ipynb 4
from torcheval.metrics import MulticlassAccuracy
from torch.utils.data import DataLoader, Subset
import numpy as np
import warnings
from learningdynamics.utils import (
    getActivation,
)
import torch
import math

# %% ../nbs/07_yinyang_pykoopman.ipynb 21
def inference_with_koopman(
    nn_model,
    dmd_model,
    test_set,
    layer_start,
    num_iterations,
    num_delays,
    num_usable_states,
    test_size=None,
):
    # Build subset
    if test_set is not None:
        subset = Subset(test_set, torch.arange(0, test_size))
    else:
        subset = test_set
    dataloader = DataLoader(dataset=subset, shuffle=True, batch_size=1000)

    hooks = []
    activation_dict = {}
    nn_model.eval()

    # Attach hooks to scaled model
    for i in range(layer_start, layer_start + (num_iterations - 1) * 2, 2):
        hooks.append(
            nn_model.features[i].register_forward_hook(
                getActivation(f"layer_{i}", activation_dict)
            )
        )

    metric = MulticlassAccuracy()

    num_supplements = math.ceil((num_delays - num_iterations + 2) / num_iterations)

    for batch in dataloader:
        # Unwrap batch
        input, target = batch
        _ = nn_model(input)

        # Grab activation
        out = torch.stack(list(activation_dict.values()))  # shape = i,t,s

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            koop_list = []
            for traj in range(out.shape[1]):
                # if num_supplements > 0:
                #     sample_id = np.random.choice(1000)
                #     pair_traj = train_states[
                #         :, sample_id * num_iterations : (sample_id * num_iterations) + num_supplements * num_iterations
                #     ].T.numpy()
                #     traj_in = np.concatenate((pair_traj, out[:, traj, :].numpy()), axis=0)

                traj_in = out[:num_delays+1, traj, :].numpy()

                Xkoop = dmd_model.simulate(
                    traj_in,
                    n_steps=(num_iterations * (num_supplements + 1)) - 1 - num_delays,
                )

                koop_list.append(torch.from_numpy(Xkoop)[-1:, :])

        koop_out = torch.cat(koop_list)[:, :num_usable_states]
        # koop_out = torch.nn.functional.relu(koop_out)

        # Feed through the rest
        for i in range(
            layer_start + (num_iterations - 1) * 2 + 1, len(nn_model.features)
        ):
            koop_out = nn_model.features[i](koop_out)

        metric.update(koop_out, target.squeeze())

    return koop_out, metric.compute()
