# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_model_trainer.ipynb.

# %% auto 0
__all__ = ['compute_model_accuracy', 'safetensors_metadata_parser', 'getActivation']

# %% ../nbs/03_model_trainer.ipynb 4
import os
from torch.nn import Module
from torch.utils.data import DataLoader, Dataset
import json
from torcheval.metrics import MulticlassAccuracy

# %% ../nbs/03_model_trainer.ipynb 20
def compute_model_accuracy(
    model: Module,  # Model
    dataset: Dataset,  # Dataset
):
    dataloader = DataLoader(dataset, batch_size=256)
    metric = MulticlassAccuracy()
    for batch in dataloader:
        image, target = batch
        output = model(image)
        metric.update(output, target.squeeze())

    return metric.compute()

# %% ../nbs/03_model_trainer.ipynb 24
def safetensors_metadata_parser(
    file_path: str,  # thing
):
    "Parse the metadata from safetensors file"
    header_size = 8
    meta_data = {}
    if os.stat(file_path).st_size > header_size:
        with open(file_path, "rb") as f:
            b8 = f.read(header_size)
            if len(b8) == header_size:
                header_len = int.from_bytes(b8, "little", signed=False)
                headers = f.read(header_len)
                if len(headers) == header_len:
                    meta_data = sorted(
                        json.loads(headers.decode("utf-8"))
                        .get("__metadata__", meta_data)
                        .items()
                    )
    meta_data_dict = {}
    for k, v in meta_data:
        meta_data_dict[k] = v
    return meta_data_dict

# %% ../nbs/03_model_trainer.ipynb 25
def getActivation(
    name: str,  # name of layer
    activation_dict: dict,  # dict to store activations,
    detach: bool = True,  # do not keep computational graph
):
    def hook(model, input, output):
        if detach:
            activation_dict[name] = output.detach()
        else:
            activation_dict[name] = output

    return hook
